database {
  host = "localhost"
  host = ${?DB_HOST}
  port = 5432
  port = ${?DB_PORT}
  database = "booking"
  database = ${?DB_NAME}
  user = "booking_user"
  user = ${?DB_USER}
  password = "booking_pass"
  password = ${?DB_PASSWORD}
}

http {
  host = "0.0.0.0"
  host = ${?HTTP_HOST}
  port = 8080
  port = ${?HTTP_PORT}
}
